//! Workspace → multiplexer-native artifact rendering. See ROADMAP v1.x
//! item 7. Pure functions; no I/O so they're easy to unit-test against
//! fixed Workspace inputs.
//!
//! Two formats today:
//!
//! - `tmux` → POSIX shell script using `tmux new-session -d` + `tmux
//!   attach`, one session per [`Session`]. Reproduces what
//!   `pa launch <name>` would do, just laid out as something you
//!   could check into a repo and `bash starter.sh` from.
//! - `zellij` → KDL layout with one tab per session. Compatible with
//!   `zellij --session <name> --layout <file>` for full-workspace
//!   spin-up in a single invocation.

use crate::domain::{Multiplexer, Workspace};
use crate::mux::sanitize_session_name;

/// Which artifact to render. The user picks via `--format`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExportFormat {
    Tmux,
    Zellij,
}

impl ExportFormat {
    /// Default format for a workspace: match its declared multiplexer.
    /// Workspaces pinned to `wezterm` fall through to tmux on the
    /// rationale that they likely want a starter script anyway and
    /// tmux is the more portable target. Caller can override with
    /// `--format` if that's wrong.
    pub fn default_for(workspace: &Workspace) -> Self {
        match workspace.multiplexer {
            Multiplexer::Tmux => ExportFormat::Tmux,
            Multiplexer::Zellij => ExportFormat::Zellij,
            Multiplexer::Wezterm => ExportFormat::Tmux,
        }
    }

    pub fn extension(&self) -> &'static str {
        match self {
            ExportFormat::Tmux => "sh",
            ExportFormat::Zellij => "kdl",
        }
    }
}

/// Top-level render. Picks the right renderer based on format.
pub fn render(workspace: &Workspace, format: ExportFormat) -> String {
    match format {
        ExportFormat::Tmux => render_tmux_script(workspace),
        ExportFormat::Zellij => render_zellij_layout(workspace),
    }
}

/// POSIX shell script that creates every workspace session in
/// detached tmux sessions, then attaches the user to the first one.
/// Empty workspaces produce a minimal script that prints a message
/// instead of crashing.
pub fn render_tmux_script(workspace: &Workspace) -> String {
    let mut out = String::new();
    out.push_str("#!/usr/bin/env bash\n");
    out.push_str(
        "# Generated by `pa export --format tmux`. See https://github.com/cybersader/portagenty\n",
    );
    out.push_str(&format!("# Workspace: {}\n", workspace.name));
    out.push_str("set -euo pipefail\n\n");

    if workspace.sessions.is_empty() {
        out.push_str("echo \"workspace has no sessions; nothing to launch\" >&2\nexit 0\n");
        return out;
    }

    for sess in &workspace.sessions {
        let name = sanitize_session_name(&sess.name);
        out.push_str(&format!("# session: {}\n", sess.name));
        out.push_str(&format!(
            "tmux has-session -t {qname} 2>/dev/null || tmux new-session -d -s {qname}",
            qname = shell_single_quote(&name),
        ));
        for (k, v) in &sess.env {
            out.push_str(&format!(
                " -e {q}",
                q = shell_single_quote(&format!("{k}={v}")),
            ));
        }
        out.push_str(&format!(
            " -c {cwd} {cmd}\n",
            cwd = shell_single_quote(&sess.cwd.display().to_string()),
            cmd = shell_single_quote(&sess.command),
        ));
    }

    let first = sanitize_session_name(&workspace.sessions[0].name);
    out.push('\n');
    out.push_str(
        "# Attach to the first session (overrides any other client; matches `pa claim` semantics).\n",
    );
    out.push_str(&format!(
        "tmux attach-session -d -t {qname}\n",
        qname = shell_single_quote(&first),
    ));
    out
}

/// KDL layout with one tab per session. Compatible with
/// `zellij --session <name> --layout <file>`.
pub fn render_zellij_layout(workspace: &Workspace) -> String {
    let mut out = String::new();
    out.push_str("// Generated by `pa export --format zellij`.\n");
    out.push_str(&format!("// Workspace: {}\n", workspace.name));

    if workspace.sessions.is_empty() {
        out.push_str("layout {\n    pane\n}\n");
        return out;
    }

    out.push_str("layout {\n");
    for (i, sess) in workspace.sessions.iter().enumerate() {
        let cwd = escape_kdl(&sess.cwd.display().to_string());
        let cmd = escape_kdl(&sess.command);
        let name = escape_kdl(&sess.name);
        let focus_attr = if i == 0 { " focus=true" } else { "" };
        out.push_str(&format!("    tab name=\"{name}\"{focus_attr} {{\n"));

        if sess.env.is_empty() {
            out.push_str(&format!(
                "        pane cwd=\"{cwd}\" {{\n            command \"bash\"\n            args \"-c\" \"{cmd}\"\n        }}\n",
            ));
        } else {
            let mut env_args = String::new();
            for (k, v) in &sess.env {
                let pair = format!("{k}={v}");
                env_args.push_str(&format!(" \"{}\"", escape_kdl(&pair)));
            }
            out.push_str(&format!(
                "        pane cwd=\"{cwd}\" {{\n            command \"env\"\n            args{env_args} \"bash\" \"-c\" \"{cmd}\"\n        }}\n",
            ));
        }

        out.push_str("    }\n");
    }
    out.push_str("}\n");
    out
}

// --- helpers ---------------------------------------------------------

/// KDL string escape — same logic as the zellij adapter; copy-pasted
/// to keep export self-contained (export shouldn't reach into the mpx
/// adapter modules for helpers).
fn escape_kdl(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str(r"\\"),
            '"' => out.push_str(r#"\""#),
            _ => out.push(c),
        }
    }
    out
}

/// Wrap a string in single quotes for safe inclusion in a bash command,
/// escaping any literal single quotes via the standard
/// `'"'"'` recipe. POSIX-portable; works in dash, bash, zsh.
fn shell_single_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for c in s.chars() {
        if c == '\'' {
            out.push_str("'\"'\"'");
        } else {
            out.push(c);
        }
    }
    out.push('\'');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::{Multiplexer, Session};
    use std::collections::BTreeMap;
    use std::path::PathBuf;

    fn ws_with(sessions: Vec<Session>) -> Workspace {
        Workspace {
            name: "Demo".into(),
            file_path: None,
            multiplexer: Multiplexer::Tmux,
            projects: vec![],
            sessions,
        }
    }

    fn sess(name: &str, cwd: &str, cmd: &str) -> Session {
        Session {
            name: name.into(),
            cwd: PathBuf::from(cwd),
            command: cmd.into(),
            kind: None,
            env: BTreeMap::new(),
        }
    }

    fn sess_env(name: &str, cwd: &str, cmd: &str, env: &[(&str, &str)]) -> Session {
        let mut m = BTreeMap::new();
        for (k, v) in env {
            m.insert((*k).into(), (*v).into());
        }
        Session {
            name: name.into(),
            cwd: PathBuf::from(cwd),
            command: cmd.into(),
            kind: None,
            env: m,
        }
    }

    // --- shell_single_quote -----------------------------------------

    #[test]
    fn shell_single_quote_wraps_simple_strings() {
        assert_eq!(shell_single_quote("hello"), "'hello'");
        assert_eq!(shell_single_quote("with space"), "'with space'");
    }

    #[test]
    fn shell_single_quote_escapes_internal_quotes() {
        assert_eq!(shell_single_quote("it's"), "'it'\"'\"'s'");
    }

    #[test]
    fn shell_single_quote_handles_empty() {
        assert_eq!(shell_single_quote(""), "''");
    }

    // --- tmux script render -----------------------------------------

    #[test]
    fn tmux_render_includes_shebang_and_set_bash_safety() {
        let ws = ws_with(vec![sess("s", "/tmp", "echo hi")]);
        let out = render_tmux_script(&ws);
        assert!(out.starts_with("#!/usr/bin/env bash\n"));
        assert!(out.contains("set -euo pipefail"));
    }

    #[test]
    fn tmux_render_emits_one_new_session_per_workspace_session() {
        let ws = ws_with(vec![
            sess("alpha", "/a", "cmd-a"),
            sess("beta", "/b", "cmd-b"),
        ]);
        let out = render_tmux_script(&ws);
        let count = out.matches("tmux new-session").count();
        assert_eq!(count, 2, "expected 2 new-session lines:\n{out}");
        assert!(out.contains("'alpha'"));
        assert!(out.contains("'beta'"));
        assert!(out.contains("'cmd-a'"));
        assert!(out.contains("'cmd-b'"));
    }

    #[test]
    fn tmux_render_attaches_to_first_session_with_dash_d() {
        let ws = ws_with(vec![
            sess("first", "/a", "cmd-a"),
            sess("second", "/b", "cmd-b"),
        ]);
        let out = render_tmux_script(&ws);
        assert!(
            out.contains("tmux attach-session -d -t 'first'"),
            "wrong attach line:\n{out}"
        );
    }

    #[test]
    fn tmux_render_emits_dash_e_per_env_var() {
        let ws = ws_with(vec![sess_env(
            "s",
            "/tmp",
            "claude",
            &[("KEY", "value with space"), ("OTHER", "v2")],
        )]);
        let out = render_tmux_script(&ws);
        // BTreeMap → alphabetical: KEY, OTHER
        assert!(
            out.contains("-e 'KEY=value with space'"),
            "missing KEY env:\n{out}"
        );
        assert!(out.contains("-e 'OTHER=v2'"), "missing OTHER env:\n{out}");
    }

    #[test]
    fn tmux_render_quotes_paths_with_spaces() {
        let ws = ws_with(vec![sess("s", "/path with space", "cmd")]);
        let out = render_tmux_script(&ws);
        assert!(
            out.contains("-c '/path with space'"),
            "cwd not quoted:\n{out}"
        );
    }

    #[test]
    fn tmux_render_handles_empty_workspace() {
        let ws = ws_with(vec![]);
        let out = render_tmux_script(&ws);
        assert!(out.contains("nothing to launch"), "unexpected: {out}");
        assert!(!out.contains("tmux new-session"));
        assert!(!out.contains("tmux attach"));
    }

    #[test]
    fn tmux_render_sanitizes_session_names() {
        let ws = ws_with(vec![sess("has spaces", "/a", "cmd")]);
        let out = render_tmux_script(&ws);
        assert!(
            out.contains("'has_spaces'"),
            "should use sanitized name:\n{out}"
        );
        // Original (un-sanitized) name still appears in the comment header.
        assert!(out.contains("# session: has spaces"));
    }

    // --- zellij layout render ---------------------------------------

    #[test]
    fn zellij_render_emits_layout_with_one_tab_per_session() {
        let ws = ws_with(vec![
            sess("alpha", "/a", "cmd-a"),
            sess("beta", "/b", "cmd-b"),
        ]);
        let out = render_zellij_layout(&ws);
        let tab_count = out.matches("tab name=").count();
        assert_eq!(tab_count, 2, "expected 2 tabs:\n{out}");
        assert!(out.contains(r#"tab name="alpha" focus=true {"#));
        assert!(out.contains(r#"tab name="beta" {"#));
    }

    #[test]
    fn zellij_render_routes_through_env_when_session_has_env() {
        let ws = ws_with(vec![sess_env("s", "/tmp", "claude", &[("MY_VAR", "v")])]);
        let out = render_zellij_layout(&ws);
        assert!(
            out.contains(r#"command "env""#),
            "missing env routing:\n{out}"
        );
        assert!(out.contains(r#""MY_VAR=v""#));
        assert!(out.contains(r#""bash" "-c" "claude""#));
    }

    #[test]
    fn zellij_render_uses_plain_bash_when_no_env() {
        let ws = ws_with(vec![sess("s", "/tmp", "claude")]);
        let out = render_zellij_layout(&ws);
        assert!(out.contains(r#"command "bash""#), "missing bash:\n{out}");
        assert!(
            !out.contains(r#"command "env""#),
            "should not route via env when env empty:\n{out}"
        );
    }

    #[test]
    fn zellij_render_handles_empty_workspace() {
        let ws = ws_with(vec![]);
        let out = render_zellij_layout(&ws);
        assert!(out.contains("layout {"));
        assert!(out.contains("pane"));
        assert!(!out.contains("tab name="));
    }

    #[test]
    fn zellij_render_escapes_quotes_in_command() {
        let ws = ws_with(vec![sess("s", "/tmp", r#"echo "hi""#)]);
        let out = render_zellij_layout(&ws);
        assert!(out.contains(r#""-c" "echo \"hi\"""#), "bad escape:\n{out}");
    }

    // --- format default ---------------------------------------------

    #[test]
    fn default_format_for_tmux_workspace_is_tmux() {
        let mut ws = ws_with(vec![]);
        ws.multiplexer = Multiplexer::Tmux;
        assert_eq!(ExportFormat::default_for(&ws), ExportFormat::Tmux);
    }

    #[test]
    fn default_format_for_zellij_workspace_is_zellij() {
        let mut ws = ws_with(vec![]);
        ws.multiplexer = Multiplexer::Zellij;
        assert_eq!(ExportFormat::default_for(&ws), ExportFormat::Zellij);
    }

    #[test]
    fn default_format_for_wezterm_falls_back_to_tmux() {
        let mut ws = ws_with(vec![]);
        ws.multiplexer = Multiplexer::Wezterm;
        assert_eq!(ExportFormat::default_for(&ws), ExportFormat::Tmux);
    }
}
